# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  mappings:
    cartes_image:
      uri_prefix: /images/cartes
      upload_destination: '%kernel.project_dir%/public/images/cartes'